### ISSUE TITLE
If possible can we have a button to update metadata so that when user switches from cennznet network it works fine

### ISSUE THREAD

**Issue by KarishmaBothara** [cennznet/bridge-ui#13]
It sometimes throws bad signature issue. which can be prevented by a updating meta from UI..

Can be solved once - https://github.com/cennznet/extension/pull/27 and https://github.com/cennznet/api.js/pull/398 are merged..and extensions new version is release on chrome/ff
but if we have update meta button, won't need to wait for other things..

**Comment by jordy25519** [comment]
let's fix the extension, the update metadata thing is not a nice ux
